### ISSUE TITLE
popen is deprecated

### ISSUE THREAD

**Issue by facastagnini** [facastagnini/zabbix-rsyslog#1]
@pvradu, I would love to get a PR for your patch https://github.com/pvradu/zabbix-rsyslog/commit/735c0d68c65e78f795ccbc5333dc36c3e7d70bd0

Thanks
Fede

**Comment by pvradu** [comment]
@facastagnini if you can explain to me what "PR" means..

**Comment by facastagnini** [comment]
PR aka Pull Request, is the way to contribute and collaborate on a project on github.

There is the official documentation here https://help.github.com/articles/using-pull-requests/

But a short version is:
1) you fork the repo with the code you want to improve
2) you work modifying the code until you are satisfied
3) you create a pull request comparing the original repo with your fork
4) the owner of the original repo can add your changes

The benefit is that we all make the software better.

I shared this code because someone else could find it useful, but also because I want to get the fixes if someone works on improving it :)

**Comment by facastagnini** [comment]
Look, I created the pull request #3 and now you improvements are present in my repo ;)
